name: Atlas
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/ci-atlas.yaml
      - 'projects/estore/inventory/migrations/*'
  pull_request:
    paths:
      - 'projects/estore/inventory/migrations/*'
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  atlas:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN_QV268S }}
      - uses: ariga/atlas-action/migrate/lint@v1
        with:
          dir: 'file://projects/estore/inventory/migrations'
          dir-name: 'showcase-project'
          config: 'file://dirs/ecommerce/atlas.hcl'
          env: 'local'
      - uses: ariga/atlas-action/migrate/push@v1
        if: github.ref == 'refs/heads/master'
        with:
          dir: 'file://projects/estore/inventory/migrations'
          dir-name: 'showcase-project'
          config: 'file://dirs/ecommerce/atlas.hcl'
          env: 'local'