name: Django CI

on:
  pull_request:
    paths:
      - 'projects/django/**'
      - '.github/workflows/django_ci.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  schema-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        working-directory: ./projects/django
        run: |
          pip install django atlas-provider-django
      - name: Set up Atlas CLI
        uses: ariga/setup-atlas@master
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - name: Set up Atlas action
        uses: ariga/atlas-action/setup@master
      - name: Atlas Schema Lint
        uses: ariga/atlas-action/schema/lint@master
        with:
          env: django
          dev-url: 'env://dev'
          url: 'env://url'