name: Setup Atlas

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_PUBLIC_TENANT_TOKEN }}
      - name: Push to Registry
        if: github.ref == 'refs/heads/master'
        uses: ariga/atlas-action/migrate/push@v1
        with:
          dir-name: 'estore-inventory'
          env: 'local'
          dir: 'file://projects/estore/inventory/migrations'
          config: 'file://projects/estore/atlas.hcl'