name: EStore Inventory Pipeline
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - 'projects/estore/inventory/migrations/*'
permissions:
  contents: read
  pull-requests: write
jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Atlas
        uses: ariga/setup-atlas@2f3c785c89a15e1c0d07bcae3900fb5feb969eea # v0
        with:
          cloud-token: ${{ secrets.ATLAS_PUBLIC_TENANT_TOKEN }}
      - name: Set up Atlas action
        uses: ariga/atlas-action/setup@d24493894b48c9f8567228edd56c4430301d9eb6 # v1
      - name: Lint Migrations
        uses: ariga/atlas-action/migrate/lint@d24493894b48c9f8567228edd56c4430301d9eb6 # v1
        with:
          dir-name: 'estore-inventory'
          dir: 'file://projects/estore/inventory/migrations'
          env: 'local'
          config: 'file://projects/estore/atlas.hcl'
      - name: Push to Registry
        if: github.ref == 'refs/heads/master'
        uses: ariga/atlas-action/migrate/push@d24493894b48c9f8567228edd56c4430301d9eb6 # v1
        with:
          dir-name: 'estore-inventory'
          env: 'local'
          dir: 'file://projects/estore/inventory/migrations'
          config: 'file://projects/estore/atlas.hcl'