name: Setup Atlas

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          token: ${{ secrets.ATLAS_PUBLIC_TENANT_TOKEN }}
      - name: push
        working-directory: projects/estore
        run: |
          atlas migrate push --env local estore-inventory