name: Atlas CI Public
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "dirs/ecommerce/migrations/*"
jobs:
  atlas:
    permissions:
      contents: read
      id-token: write
    services:
      mysql:
        image: mysql:8.0.29
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: dev
        ports:
          - "3306:3306"
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Atlas
        uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_PUBLIC_TENANT_TOKEN }}
      - name: Lint
        uses: ariga/atlas-action/migrate/lint@v1
        if: github.ref != 'refs/heads/master'
        with:
          dir: file://dirs/ecommerce/migrations
          dir-name: ariga-atlas-showcase-dirs-ecommerce-migrations
          dev-url: mysql://root:pass@localhost:3306/dev
      - name: Push
        if: github.ref == 'refs/heads/master'
        uses: ariga/atlas-action/migrate/push@v1
        with:
          dir: file://dirs/ecommerce/migrations
          dir-name: ariga-atlas-showcase-dirs-ecommerce-migrations
          dev-url: mysql://root:pass@localhost:3306/dev
          tag: ${{ github.sha }}
