name: GORM CI

on:
  pull_request:
    paths:
      - 'projects/gorm/**'
      - '.github/workflows/gorm_ci.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  schema-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: '1.24'
      - name: Set up Atlas CLI
        uses: ariga/setup-atlas@2f3c785c89a15e1c0d07bcae3900fb5feb969eea # v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - name: Set up Atlas action
        uses: ariga/atlas-action/setup@d24493894b48c9f8567228edd56c4430301d9eb6 # v1
      - name: Atlas Schema Lint
        uses: ariga/atlas-action/schema/lint@d24493894b48c9f8567228edd56c4430301d9eb6 # v1
        with:
          working-directory: ./projects/gorm
          env: gorm
          dev-url: 'sqlite://?mode=memory&_fk=1'
          url: 'env://url'