name: GORM CI

on:
  pull_request:
    paths:
      - 'projects/gorm/**'
      - '.github/workflows/gorm_ci.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  schema-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Set up Atlas CLI
        uses: ariga/setup-atlas@master
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - name: Set up Atlas action
        uses: ariga/atlas-action/setup@master
      - name: Atlas Schema Lint
        uses: ariga/atlas-action/schema/lint@master
        with:
          working-directory: ./projects/gorm
          env: gorm
          dev-url: 'sqlite://?mode=memory&_fk=1'
          url: 'env://url'