name: Sequelize TS CI

on:
  pull_request:
    paths:
      - 'projects/sequelize-ts/**'
      - '.github/workflows/sequelize-ts_ci.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  schema-lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        working-directory: ./projects/sequelize-ts
        run: |
          npm install
      - name: Set up Atlas CLI
        uses: ariga/setup-atlas@master
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - name: Set up Atlas action
        uses: ariga/atlas-action/setup@master
      - name: Atlas Schema Lint
        uses: ariga/atlas-action/schema/lint@master
        with:
          working-directory: ./projects/sequelize-ts
          env: sequelize
          dev-url: 'sqlite://?mode=memory&_fk=1'
          url: 'env://url'