name: Sync Werft
on:
  push:
    branches:
      - master
    paths:
      - 'dirs/werft/*'
  workflow_dispatch:
jobs:
  sync:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/atlas-sync-action@v0
        with:
          dir: 'dirs/werft'
          dir-format: golang-migrate
          driver: postgres
          cloud-public: true
