name: Sync Exposure Notifications Server
on:
  push:
    branches:
      - master
    paths:
      - 'dirs/exposure-notifications-server/*'
  workflow_dispatch:
jobs:
  sync:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: ariga/atlas-sync-action@2ca31f55e863b6736956424c5710862653813401 # v0
        with:
          dir: 'dirs/exposure-notifications-server'
          dir-format: golang-migrate
          driver: postgres
          cloud-public: true
