name: Sync Kratos
on:
  push:
    branches:
      - master
jobs:
  sync:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/atlas-sync-action@v0
        with:
          dir: 'dirs/migrations'
          driver: mysql
          cloud-url: https://api.atlasgo.link
          cloud-public: true
